name: Build and Test with Premake

on:
  push:
    branches:
      - main  # Adjust branch name if necessary
  pull_request:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Premake
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz
          tar -xzf premake-5.0.0-alpha16-linux.tar.gz
          mv premake5 /usr/local/bin/premake
          premake5 --version  # Verify Premake installation

      - name: Generate build files with Premake
        run: premake5 --file=premake5.lua --os=linux gmake  # Adjust Premake script and OS as necessary

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Replace with your desired .NET version

      - name: Restore dependencies
        run: dotnet restore src/Meowsterpiece.sln  # Adjust path to your solution file

      - name: Build
        run: dotnet build src/Meowsterpiece.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test src/Meowsterpiece.sln --configuration Release --no-build --verbosity normal
